spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 5591b2f9d2b4599d07d3
            clientSecret: 862d4bd5c7969bc5310264abd5bab92e25d47d52
# ...